"""
Training agent for UAV-UGV cooperative routing.

The agent combines three learning stages:

    1. Behavioral Cloning (BC)
       Learn from expert trajectories generated by the heuristic /
       OR-Tools planner.

    2. Proximal Policy Optimization (PPO)
       Fine-tune the policy using reinforcement learning.

    3. Self-Imitation Learning (SIL)
       Replay high-quality trajectories discovered during training.

The policy network itself is implemented in ``model.py``.

Typical pipeline
----------------

Expert planner
      |
      v
Behavioral Cloning
      |
      v
PPO Fine-tuning
      |
      v
Best trajectories
      |
      v
Self-Imitation Learning
"""

from __future__ import annotations

import copy
import random
from contextlib import nullcontext
from pathlib import Path
from typing import Any, Mapping, Sequence

import numpy as np
import torch
import torch.nn.functional as F
from torch import Tensor
from torch.distributions import Categorical
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingWarmRestarts

from .model import (
    ScalableTransformerPolicy,
    build_policy,
)

# ============================================================
# Type aliases
# ============================================================

Action = list[int]
Trajectory = dict[str, Any]


# ============================================================
# Device helpers
# ============================================================


def get_default_device() -> torch.device:
    """
    Return the preferred PyTorch device.
    """

    if torch.cuda.is_available():
        return torch.device("cuda")

    if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return torch.device("mps")

    return torch.device("cpu")


# ============================================================
# Agent
# ============================================================


class SuperiorityAgent:
    """
    BC + PPO + SIL agent for UAV-UGV cooperative routing.

    Parameters
    ----------
    num_tasks:
        Number of task nodes excluding the depot.

    is_large:
        Whether to use the larger model configuration.

        False:
            embed_dim = 192
            heads = 6
            layers = 3

        True:
            embed_dim = 256
            heads = 8
            layers = 4

    lr:
        Base learning rate.

        For large instances, the original training configuration
        uses ``lr * 0.7``.

    bc_weight:
        Loss weight used during Behavioral Cloning.

    sil_weight:
        Loss weight used during Self-Imitation Learning.

    gamma:
        PPO discount factor.

        Defaults:
            small / medium -> 0.99
            large          -> 0.995

    gae_lambda:
        GAE lambda parameter.

    clip_eps:
        PPO clipping epsilon.

    ppo_epochs:
        PPO optimization epochs per trajectory.

        Defaults:
            small / medium -> 3
            large          -> 4

    entropy_coef:
        Initial entropy coefficient.

        Defaults:
            small / medium -> 0.05
            large          -> 0.08

    entropy_min:
        Minimum entropy coefficient.

    dropout:
        Transformer dropout.

    weight_decay:
        AdamW weight decay.

    max_best_buffer:
        Maximum number of trajectories retained for SIL.

    device:
        PyTorch device.

    use_amp:
        Enable automatic mixed precision on CUDA.

    compile_model:
        Optionally enable ``torch.compile`` on supported CUDA systems.

    grad_clip_bc:
        Maximum gradient norm during BC.

    grad_clip_ppo:
        Maximum gradient norm during PPO.
    """

    def __init__(
        self,
        num_tasks: int,
        *,
        is_large: bool = False,
        lr: float = 2e-4,
        bc_weight: float = 1.0,
        sil_weight: float = 0.5,
        gamma: float | None = None,
        gae_lambda: float = 0.95,
        clip_eps: float = 0.2,
        ppo_epochs: int | None = None,
        entropy_coef: float | None = None,
        entropy_min: float = 0.01,
        dropout: float = 0.1,
        weight_decay: float = 1e-4,
        max_best_buffer: int | None = None,
        scheduler_t0: int = 100,
        scheduler_t_mult: int = 2,
        scheduler_eta_min: float = 1e-6,
        grad_clip_bc: float = 1.0,
        grad_clip_ppo: float = 0.5,
        device: str | torch.device | None = None,
        use_amp: bool | None = None,
        compile_model: bool = False,
    ) -> None:

        if num_tasks <= 0:
            raise ValueError("num_tasks must be greater than 0.")

        if lr <= 0:
            raise ValueError("lr must be greater than 0.")

        if not 0.0 < gae_lambda <= 1.0:
            raise ValueError("gae_lambda must be in (0, 1].")

        if not 0.0 < clip_eps < 1.0:
            raise ValueError("clip_eps must be in (0, 1).")

        self.num_tasks = int(num_tasks)
        self.is_large = bool(is_large)

        # ====================================================
        # Device
        # ====================================================

        if device is None:
            self.device = get_default_device()
        else:
            self.device = torch.device(device)

        if use_amp is None:
            self.use_amp = self.device.type == "cuda"
        else:
            self.use_amp = bool(use_amp) and self.device.type == "cuda"

        # ====================================================
        # Hyperparameters
        # ====================================================

        self.base_lr = float(lr)

        # Original large-scale setting:
        #
        # learning_rate = lr * 0.7
        self.learning_rate = (
            self.base_lr * 0.7 if self.is_large else self.base_lr
        )

        self.bc_weight = float(bc_weight)

        self.sil_weight = float(sil_weight)

        self.gamma = (
            float(gamma)
            if gamma is not None
            else (0.995 if self.is_large else 0.99)
        )

        self.gae_lambda = float(gae_lambda)

        self.clip_eps = float(clip_eps)

        self.ppo_epochs = (
            int(ppo_epochs)
            if ppo_epochs is not None
            else (4 if self.is_large else 3)
        )

        self.entropy_coef_init = (
            float(entropy_coef)
            if entropy_coef is not None
            else (0.08 if self.is_large else 0.05)
        )

        self.entropy_coef = self.entropy_coef_init

        self.entropy_min = float(entropy_min)

        self.weight_decay = float(weight_decay)

        self.grad_clip_bc = float(grad_clip_bc)

        self.grad_clip_ppo = float(grad_clip_ppo)

        self.max_best_buffer = (
            int(max_best_buffer)
            if max_best_buffer is not None
            else (100 if self.is_large else 50)
        )

        # ====================================================
        # Model
        # ====================================================

        self._base_policy = build_policy(
            is_large=self.is_large,
            dropout=dropout,
        ).to(self.device)

        self.policy = self._base_policy

        self.compile_model = False

        if (
            compile_model
            and self.device.type == "cuda"
            and hasattr(torch, "compile")
        ):

            try:

                self.policy = torch.compile(
                    self._base_policy,
                    mode="reduce-overhead",
                    fullgraph=False,
                )

                self.compile_model = True

            except Exception:

                # Compilation is optional.
                self.policy = self._base_policy

                self.compile_model = False

        # ====================================================
        # Optimizer
        # ====================================================

        optimizer_kwargs = {
            "lr": self.learning_rate,
            "weight_decay": self.weight_decay,
        }

        if self.device.type == "cuda":

            try:

                self.optimizer = AdamW(
                    self._base_policy.parameters(),
                    fused=True,
                    **optimizer_kwargs,
                )

            except (
                TypeError,
                RuntimeError,
            ):

                self.optimizer = AdamW(
                    self._base_policy.parameters(),
                    **optimizer_kwargs,
                )

        else:

            self.optimizer = AdamW(
                self._base_policy.parameters(),
                **optimizer_kwargs,
            )

        # ====================================================
        # Learning-rate scheduler
        # ====================================================

        self.scheduler = CosineAnnealingWarmRestarts(
            self.optimizer,
            T_0=scheduler_t0,
            T_mult=scheduler_t_mult,
            eta_min=scheduler_eta_min,
        )

        # ====================================================
        # AMP scaler
        # ====================================================

        self.scaler = None

        if self.use_amp:

            try:
                self.scaler = torch.amp.GradScaler("cuda")

            except (
                AttributeError,
                TypeError,
            ):

                self.scaler = torch.cuda.amp.GradScaler()

        # ====================================================
        # Self-Imitation buffer
        # ====================================================

        self.best_trajectories: list[dict[str, Any]] = []

        # Number of PPO updates.
        self.update_count = 0

        # Save constructor information with checkpoints.
        self.config = {
            "num_tasks": self.num_tasks,
            "is_large": self.is_large,
            "lr": self.base_lr,
            "bc_weight": self.bc_weight,
            "sil_weight": self.sil_weight,
            "gamma": self.gamma,
            "gae_lambda": self.gae_lambda,
            "clip_eps": self.clip_eps,
            "ppo_epochs": self.ppo_epochs,
            "entropy_coef": self.entropy_coef_init,
            "entropy_min": self.entropy_min,
            "dropout": float(dropout),
            "weight_decay": self.weight_decay,
            "max_best_buffer": (self.max_best_buffer),
        }

    # ========================================================
    # Context helpers
    # ========================================================

    def _autocast_context(self):
        """
        Return CUDA AMP context when AMP is enabled.
        """

        if self.use_amp:
            return torch.amp.autocast(
                device_type="cuda",
                dtype=torch.float16,
            )

        return nullcontext()

    # ========================================================
    # Tensor helpers
    # ========================================================

    def _observation_to_device(
        self,
        observation: Mapping[
            str,
            np.ndarray | Tensor,
        ],
    ) -> dict[str, Tensor]:
        """
        Convert one environment observation to batched tensors.
        """

        required_keys = (
            "nodes_features",
            "uav_state",
            "ugv_state",
        )

        converted: dict[str, Tensor] = {}

        for key in required_keys:

            if key not in observation:
                raise KeyError(f"Observation is missing '{key}'.")

            tensor = torch.as_tensor(
                observation[key],
                dtype=torch.float32,
                device=self.device,
            )

            converted[key] = tensor.unsqueeze(0)

        return converted

    def _stack_observations(
        self,
        observations: Sequence[Mapping[str, Any]],
    ) -> dict[str, Tensor]:
        """
        Stack trajectory observations into tensors.
        """

        if len(observations) == 0:
            raise ValueError("Cannot stack an empty observation list.")

        required_keys = (
            "nodes_features",
            "uav_state",
            "ugv_state",
        )

        result: dict[str, Tensor] = {}

        for key in required_keys:

            arrays = [
                np.asarray(
                    observation[key],
                    dtype=np.float32,
                )
                for observation in observations
            ]

            result[key] = torch.as_tensor(
                np.stack(
                    arrays,
                    axis=0,
                ),
                dtype=torch.float32,
                device=self.device,
            )

        return result

    def _prepare_masks(
        self,
        uav_mask: np.ndarray | Tensor,
        ugv_mask: np.ndarray | Tensor,
        mode_mask: np.ndarray | Tensor,
    ) -> tuple[
        Tensor,
        Tensor,
        Tensor,
    ]:

        uav_tensor = torch.as_tensor(
            uav_mask,
            dtype=torch.bool,
            device=self.device,
        )

        ugv_tensor = torch.as_tensor(
            ugv_mask,
            dtype=torch.bool,
            device=self.device,
        )

        mode_tensor = torch.as_tensor(
            mode_mask,
            dtype=torch.bool,
            device=self.device,
        )

        if uav_tensor.dim() == 1:
            uav_tensor = uav_tensor.unsqueeze(0)

        if ugv_tensor.dim() == 1:
            ugv_tensor = ugv_tensor.unsqueeze(0)

        if mode_tensor.dim() == 1:
            mode_tensor = mode_tensor.unsqueeze(0)

        if not torch.any(uav_tensor):
            raise ValueError("UAV action mask contains no valid action.")

        if not torch.any(ugv_tensor):
            raise ValueError("UGV action mask contains no valid action.")

        if not torch.any(mode_tensor):
            raise ValueError("Mode action mask contains no valid action.")

        return (
            uav_tensor,
            ugv_tensor,
            mode_tensor,
        )

    # ========================================================
    # Action selection
    # ========================================================

    @torch.inference_mode()
    def select_action(
        self,
        observation: Mapping[str, Any],
        uav_mask: np.ndarray | Tensor,
        ugv_mask: np.ndarray | Tensor,
        mode_mask: np.ndarray | Tensor,
        *,
        temperature: float = 1.0,
        expert_action: Sequence[int] | None = None,
        deterministic: bool = False,
    ) -> tuple[
        Action,
        float,
    ]:
        """
        Select one UAV-UGV action.

        Parameters
        ----------
        observation:
            Environment observation.

        uav_mask:
            Valid UAV destinations.

        ugv_mask:
            Valid UGV destinations.

        mode_mask:
            Valid operating modes.

        temperature:
            Sampling temperature.

            > 1:
                more exploration

            < 1:
                more deterministic

        expert_action:
            Optional forced action used during expert replay.

        deterministic:
            Select argmax actions instead of sampling.

        Returns
        -------
        action:
            [
                uav_target,
                ugv_target,
                mode,
            ]

        log_probability:
            Sum of the three action log-probabilities.
        """

        if temperature <= 0:
            raise ValueError("temperature must be greater than 0.")

        obs_tensor = self._observation_to_device(observation)

        (
            uav_mask_tensor,
            ugv_mask_tensor,
            mode_mask_tensor,
        ) = self._prepare_masks(
            uav_mask,
            ugv_mask,
            mode_mask,
        )

        with self._autocast_context():

            (
                uav_distribution,
                ugv_distribution,
                mode_distribution,
                _,
            ) = self.policy(
                obs_tensor,
                uav_mask_tensor,
                ugv_mask_tensor,
                mode_mask_tensor,
                self.num_tasks,
            )

        # ----------------------------------------------------
        # Temperature
        # ----------------------------------------------------

        if temperature != 1.0:

            uav_distribution = Categorical(
                logits=(uav_distribution.logits / temperature)
            )

            ugv_distribution = Categorical(
                logits=(ugv_distribution.logits / temperature)
            )

            mode_distribution = Categorical(
                logits=(mode_distribution.logits / temperature)
            )

        # ----------------------------------------------------
        # Expert action
        # ----------------------------------------------------

        if expert_action is not None:

            if len(expert_action) != 3:
                raise ValueError(
                    "expert_action must contain "
                    "[uav_target, ugv_target, mode]."
                )

            uav_action = torch.tensor(
                [int(expert_action[0])],
                device=self.device,
                dtype=torch.long,
            )

            ugv_action = torch.tensor(
                [int(expert_action[1])],
                device=self.device,
                dtype=torch.long,
            )

            mode_action = torch.tensor(
                [int(expert_action[2])],
                device=self.device,
                dtype=torch.long,
            )

        # ----------------------------------------------------
        # Deterministic evaluation
        # ----------------------------------------------------

        elif deterministic:

            uav_action = torch.argmax(
                uav_distribution.logits,
                dim=-1,
            )

            ugv_action = torch.argmax(
                ugv_distribution.logits,
                dim=-1,
            )

            mode_action = torch.argmax(
                mode_distribution.logits,
                dim=-1,
            )

        # ----------------------------------------------------
        # Stochastic sampling
        # ----------------------------------------------------

        else:

            uav_action = uav_distribution.sample()

            ugv_action = ugv_distribution.sample()

            mode_action = mode_distribution.sample()

        log_probability = (
            uav_distribution.log_prob(uav_action)
            + ugv_distribution.log_prob(ugv_action)
            + mode_distribution.log_prob(mode_action)
        )

        action = [
            int(uav_action.item()),
            int(ugv_action.item()),
            int(mode_action.item()),
        ]

        return (
            action,
            float(log_probability.item()),
        )

    # ========================================================
    # Gradient step helper
    # ========================================================

    def _optimizer_step(
        self,
        loss: Tensor,
        *,
        max_grad_norm: float,
    ) -> None:
        """
        Perform one optimizer step with optional AMP.
        """

        self.optimizer.zero_grad(set_to_none=True)

        if self.use_amp and self.scaler is not None:

            self.scaler.scale(loss).backward()

            # Unscale before gradient clipping.
            self.scaler.unscale_(self.optimizer)

            torch.nn.utils.clip_grad_norm_(
                self._base_policy.parameters(),
                max_grad_norm,
            )

            self.scaler.step(self.optimizer)

            self.scaler.update()

        else:

            loss.backward()

            torch.nn.utils.clip_grad_norm_(
                self._base_policy.parameters(),
                max_grad_norm,
            )

            self.optimizer.step()

    # ========================================================
    # Behavioral Cloning
    # ========================================================

    def behavioral_cloning_update(
        self,
        expert_trajectories: Sequence[Trajectory],
        *,
        loss_weight: float | None = None,
    ) -> float:
        """
        Train the policy using expert trajectories.

        The whole trajectory is processed in one batched
        forward pass.

        Loss:

            L_BC =
                CE(UAV)
                + CE(UGV)
                + CE(mode)

        Parameters
        ----------
        expert_trajectories:
            Expert trajectories.

        loss_weight:
            Optional loss multiplier.

            Defaults to ``self.bc_weight``.
        """

        if len(expert_trajectories) == 0:
            return 0.0

        if loss_weight is None:
            loss_weight = self.bc_weight

        if loss_weight <= 0:
            return 0.0

        self.policy.train()

        total_loss = 0.0
        update_count = 0

        for trajectory in expert_trajectories:

            states = trajectory.get(
                "states",
                [],
            )

            trajectory_length = len(states)

            if trajectory_length == 0:
                continue

            # ------------------------------------------------
            # Observations
            # ------------------------------------------------

            observations = self._stack_observations(states)

            # ------------------------------------------------
            # Masks
            # ------------------------------------------------

            uav_masks = torch.as_tensor(
                np.asarray(
                    trajectory["uav_masks"],
                    dtype=bool,
                ),
                dtype=torch.bool,
                device=self.device,
            )

            ugv_masks = torch.as_tensor(
                np.asarray(
                    trajectory["ugv_masks"],
                    dtype=bool,
                ),
                dtype=torch.bool,
                device=self.device,
            )

            mode_masks = torch.as_tensor(
                np.asarray(
                    trajectory["mode_masks"],
                    dtype=bool,
                ),
                dtype=torch.bool,
                device=self.device,
            )

            # ------------------------------------------------
            # Expert actions
            # ------------------------------------------------

            expert_actions = torch.as_tensor(
                trajectory["actions"],
                dtype=torch.long,
                device=self.device,
            )

            if expert_actions.dim() != 2 or expert_actions.size(1) != 3:
                raise ValueError(
                    "Trajectory actions must have " "shape [T, 3]."
                )

            # ------------------------------------------------
            # Forward
            # ------------------------------------------------

            with self._autocast_context():

                (
                    uav_logits,
                    ugv_logits,
                    mode_logits,
                    _,
                ) = self.policy.batched_forward(
                    observations,
                    uav_masks,
                    ugv_masks,
                    mode_masks,
                    self.num_tasks,
                )

                uav_loss = F.cross_entropy(
                    uav_logits,
                    expert_actions[:, 0],
                )

                ugv_loss = F.cross_entropy(
                    ugv_logits,
                    expert_actions[:, 1],
                )

                mode_loss = F.cross_entropy(
                    mode_logits,
                    expert_actions[:, 2],
                )

                raw_bc_loss = uav_loss + ugv_loss + mode_loss

                loss = float(loss_weight) * raw_bc_loss

            self._optimizer_step(
                loss,
                max_grad_norm=self.grad_clip_bc,
            )

            total_loss += float(raw_bc_loss.detach().item())

            update_count += 1

        if update_count == 0:
            return 0.0

        return total_loss / update_count

    # ========================================================
    # GAE
    # ========================================================

    def _compute_gae(
        self,
        rewards: Tensor,
        dones: Tensor,
        values: Tensor,
    ) -> tuple[
        Tensor,
        Tensor,
    ]:
        """
        Compute Generalized Advantage Estimation.

        Returns
        -------
        advantages
        returns
        """

        trajectory_length = rewards.shape[0]

        next_values = torch.cat(
            [
                values[1:],
                torch.zeros(
                    1,
                    device=self.device,
                    dtype=values.dtype,
                ),
            ]
        )

        deltas = rewards + self.gamma * next_values * (1.0 - dones) - values

        advantages = torch.zeros_like(rewards)

        gae = torch.tensor(
            0.0,
            device=self.device,
            dtype=rewards.dtype,
        )

        for timestep in reversed(range(trajectory_length)):

            gae = (
                deltas[timestep]
                + self.gamma * self.gae_lambda * (1.0 - dones[timestep]) * gae
            )

            advantages[timestep] = gae

        returns = advantages + values

        # unbiased=False prevents NaN when trajectory length = 1.
        advantage_std = advantages.std(unbiased=False)

        advantages = (advantages - advantages.mean()) / (advantage_std + 1e-8)

        return (
            advantages,
            returns,
        )

    # ========================================================
    # PPO update
    # ========================================================

    def rl_update(
        self,
        memory: Trajectory,
    ) -> tuple[
        float,
        float,
        float,
    ]:
        """
        Perform one PPO update.

        Required memory keys
        --------------------
        states
        actions
        logprobs
        rewards
        is_terminals
        uav_masks
        ugv_masks
        mode_masks

        Returns
        -------
        actor_loss
        critic_loss
        mean_entropy
        """

        states = memory.get(
            "states",
            [],
        )

        trajectory_length = len(states)

        if trajectory_length == 0:
            return (
                0.0,
                0.0,
                0.0,
            )

        self.policy.train()

        # ====================================================
        # Prepare trajectory
        # ====================================================

        old_logprobs = torch.as_tensor(
            memory["logprobs"],
            dtype=torch.float32,
            device=self.device,
        )

        actions = torch.as_tensor(
            memory["actions"],
            dtype=torch.long,
            device=self.device,
        )

        rewards = torch.as_tensor(
            memory["rewards"],
            dtype=torch.float32,
            device=self.device,
        )

        dones = torch.as_tensor(
            memory["is_terminals"],
            dtype=torch.float32,
            device=self.device,
        )

        uav_masks = torch.as_tensor(
            np.asarray(
                memory["uav_masks"],
                dtype=bool,
            ),
            dtype=torch.bool,
            device=self.device,
        )

        ugv_masks = torch.as_tensor(
            np.asarray(
                memory["ugv_masks"],
                dtype=bool,
            ),
            dtype=torch.bool,
            device=self.device,
        )

        mode_masks = torch.as_tensor(
            np.asarray(
                memory["mode_masks"],
                dtype=bool,
            ),
            dtype=torch.bool,
            device=self.device,
        )

        observations = self._stack_observations(states)

        # ====================================================
        # Values + GAE
        # ====================================================

        with torch.no_grad():

            with self._autocast_context():

                (
                    _,
                    _,
                    _,
                    values,
                ) = self.policy.batched_forward(
                    observations,
                    uav_masks,
                    ugv_masks,
                    mode_masks,
                    self.num_tasks,
                )

            values = values.float()

            (
                advantages,
                returns,
            ) = self._compute_gae(
                rewards=rewards,
                dones=dones,
                values=values,
            )

        # ====================================================
        # PPO epochs
        # ====================================================

        total_actor_loss = 0.0
        total_critic_loss = 0.0
        total_entropy = 0.0

        for _ in range(self.ppo_epochs):

            with self._autocast_context():

                (
                    uav_logits,
                    ugv_logits,
                    mode_logits,
                    predicted_values,
                ) = self.policy.batched_forward(
                    observations,
                    uav_masks,
                    ugv_masks,
                    mode_masks,
                    self.num_tasks,
                )

                # --------------------------------------------
                # Distributions
                # --------------------------------------------

                uav_distribution = Categorical(logits=uav_logits)

                ugv_distribution = Categorical(logits=ugv_logits)

                mode_distribution = Categorical(logits=mode_logits)

                # --------------------------------------------
                # Joint action log probability
                # --------------------------------------------

                new_logprobs = (
                    uav_distribution.log_prob(actions[:, 0])
                    + ugv_distribution.log_prob(actions[:, 1])
                    + mode_distribution.log_prob(actions[:, 2])
                )

                # --------------------------------------------
                # Joint entropy
                # --------------------------------------------

                entropy = (
                    uav_distribution.entropy()
                    + ugv_distribution.entropy()
                    + mode_distribution.entropy()
                )

                # --------------------------------------------
                # PPO probability ratio
                # --------------------------------------------

                log_ratio = new_logprobs - old_logprobs

                # Avoid numerical overflow.
                ratio = torch.exp(
                    torch.clamp(
                        log_ratio,
                        min=-20.0,
                        max=10.0,
                    )
                )

                # --------------------------------------------
                # PPO clipped actor objective
                # --------------------------------------------

                surrogate_1 = ratio * advantages

                surrogate_2 = (
                    torch.clamp(
                        ratio,
                        1.0 - self.clip_eps,
                        1.0 + self.clip_eps,
                    )
                    * advantages
                )

                actor_loss = -torch.min(
                    surrogate_1,
                    surrogate_2,
                ).mean()

                # --------------------------------------------
                # Value loss
                # --------------------------------------------

                critic_loss = 0.5 * F.mse_loss(
                    predicted_values.float(),
                    returns,
                )

                # --------------------------------------------
                # Entropy exploration bonus
                # --------------------------------------------

                entropy_loss = -self.entropy_coef * entropy.mean()

                total_loss = actor_loss + critic_loss + entropy_loss

            self._optimizer_step(
                total_loss,
                max_grad_norm=(self.grad_clip_ppo),
            )

            total_actor_loss += float(actor_loss.detach().item())

            total_critic_loss += float(critic_loss.detach().item())

            total_entropy += float(entropy.detach().mean().item())

        # ====================================================
        # Entropy decay
        # ====================================================

        self.update_count += 1

        entropy_decay = 0.9995 if self.is_large else 0.999

        self.entropy_coef = max(
            self.entropy_min,
            self.entropy_coef * entropy_decay,
        )

        # ====================================================
        # Learning-rate scheduler
        # ====================================================

        self.scheduler.step()

        return (
            total_actor_loss / self.ppo_epochs,
            total_critic_loss / self.ppo_epochs,
            total_entropy / self.ppo_epochs,
        )

    # ========================================================
    # Backward-compatible PPO name
    # ========================================================

    def update(
        self,
        memory: Trajectory,
    ) -> tuple[
        float,
        float,
        float,
    ]:
        """
        Alias for ``rl_update``.
        """

        return self.rl_update(memory)

    # ========================================================
    # Self-Imitation Learning buffer
    # ========================================================

    def add_best_trajectory(
        self,
        trajectory: Trajectory,
        makespan: float,
        baseline_makespan: float,
    ) -> bool:
        """
        Store a trajectory for SIL if it improves on the baseline.

        Parameters
        ----------
        trajectory:
            RL trajectory.

        makespan:
            Makespan achieved by the RL agent.

        baseline_makespan:
            Expert / OR-Tools baseline makespan.

        Returns
        -------
        bool
            True if the trajectory was added.
        """

        if baseline_makespan <= 0:
            return False

        if makespan >= baseline_makespan:
            return False

        improvement = (baseline_makespan - makespan) / baseline_makespan

        self.best_trajectories.append(
            {
                "trajectory": copy.deepcopy(trajectory),
                "makespan": float(makespan),
                "improvement": float(improvement),
            }
        )

        # Best makespan first.
        self.best_trajectories.sort(key=lambda item: item["makespan"])

        self.best_trajectories = self.best_trajectories[: self.max_best_buffer]

        return True

    def self_imitation_update(
        self,
    ) -> float:
        """
        Perform one SIL update using a previously discovered
        high-quality trajectory.
        """

        if len(self.best_trajectories) == 0:
            return 0.0

        best_item = random.choice(self.best_trajectories)

        trajectory = best_item["trajectory"]

        return self.behavioral_cloning_update(
            [trajectory],
            loss_weight=self.sil_weight,
        )

    # ========================================================
    # Buffer utilities
    # ========================================================

    def clear_sil_buffer(
        self,
    ) -> None:
        """
        Remove all stored SIL trajectories.
        """

        self.best_trajectories.clear()

    @property
    def sil_buffer_size(
        self,
    ) -> int:
        """
        Number of trajectories currently stored for SIL.
        """

        return len(self.best_trajectories)

    # ========================================================
    # Entropy utilities
    # ========================================================

    def reset_entropy(
        self,
    ) -> None:
        """
        Reset entropy coefficient to its initial value.
        """

        self.entropy_coef = self.entropy_coef_init

    # ========================================================
    # Learning-rate information
    # ========================================================

    @property
    def current_lr(
        self,
    ) -> float:
        """
        Current optimizer learning rate.
        """

        return float(self.optimizer.param_groups[0]["lr"])

    # ========================================================
    # Model information
    # ========================================================

    @property
    def num_parameters(
        self,
    ) -> int:
        """
        Number of trainable policy parameters.
        """

        return sum(
            parameter.numel()
            for parameter in self._base_policy.parameters()
            if parameter.requires_grad
        )

    # ========================================================
    # Train / evaluation mode
    # ========================================================

    def train(
        self,
    ) -> None:
        """
        Put policy into training mode.
        """

        self.policy.train()

    def eval(
        self,
    ) -> None:
        """
        Put policy into evaluation mode.
        """

        self.policy.eval()

    # ========================================================
    # Checkpoints
    # ========================================================

    def save(
        self,
        path: str | Path,
        *,
        include_optimizer: bool = True,
        include_sil_buffer: bool = False,
    ) -> None:
        """
        Save a training checkpoint.

        Parameters
        ----------
        path:
            Output checkpoint path.

        include_optimizer:
            Save optimizer and scheduler states.

        include_sil_buffer:
            Save stored SIL trajectories.

            This may substantially increase checkpoint size.
        """

        checkpoint_path = Path(path)

        checkpoint_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        checkpoint: dict[str, Any] = {
            "format_version": 1,
            "policy_state_dict": (self._base_policy.state_dict()),
            "agent_config": (self.config.copy()),
            "entropy_coef": (self.entropy_coef),
            "update_count": (self.update_count),
        }

        if include_optimizer:

            checkpoint["optimizer_state_dict"] = self.optimizer.state_dict()

            checkpoint["scheduler_state_dict"] = self.scheduler.state_dict()

        if include_sil_buffer:

            checkpoint["best_trajectories"] = self.best_trajectories

        torch.save(
            checkpoint,
            checkpoint_path,
        )

    def load(
        self,
        path: str | Path,
        *,
        load_optimizer: bool = True,
        load_sil_buffer: bool = True,
    ) -> None:
        """
        Load a checkpoint.

        This method also supports a raw model state_dict saved
        by older versions of the project.
        """

        checkpoint_path = Path(path)

        if not checkpoint_path.exists():
            raise FileNotFoundError(checkpoint_path)

        try:

            checkpoint = torch.load(
                checkpoint_path,
                map_location=self.device,
                weights_only=False,
            )

        except TypeError:

            # Compatibility with older PyTorch versions.
            checkpoint = torch.load(
                checkpoint_path,
                map_location=self.device,
            )

        # ----------------------------------------------------
        # New checkpoint format
        # ----------------------------------------------------

        if (
            isinstance(
                checkpoint,
                dict,
            )
            and "policy_state_dict" in checkpoint
        ):

            self._base_policy.load_state_dict(checkpoint["policy_state_dict"])

            if load_optimizer and "optimizer_state_dict" in checkpoint:

                self.optimizer.load_state_dict(
                    checkpoint["optimizer_state_dict"]
                )

            if load_optimizer and "scheduler_state_dict" in checkpoint:

                self.scheduler.load_state_dict(
                    checkpoint["scheduler_state_dict"]
                )

            self.entropy_coef = float(
                checkpoint.get(
                    "entropy_coef",
                    self.entropy_coef_init,
                )
            )

            self.update_count = int(
                checkpoint.get(
                    "update_count",
                    0,
                )
            )

            if load_sil_buffer and "best_trajectories" in checkpoint:

                self.best_trajectories = checkpoint["best_trajectories"]

        # ----------------------------------------------------
        # Legacy raw state_dict
        # ----------------------------------------------------

        else:

            self._base_policy.load_state_dict(checkpoint)


# ============================================================
# Recommended generic name
# ============================================================

UAVUGVAgent = SuperiorityAgent


# ============================================================
# Public API
# ============================================================

__all__ = [
    "Action",
    "Trajectory",
    "get_default_device",
    "SuperiorityAgent",
    "UAVUGVAgent",
]
