"""
Transformer-based policy network for UAV-UGV cooperative routing.

Architecture
------------
Node features
    -> Node embedding
    -> Transformer encoder
    -> Graph embedding

UAV state
    -> UAV embedding

UGV state
    -> UGV embedding

Problem scale
    -> Scale embedding

All context representations are fused and used by:

    1. UAV pointer head
    2. UGV pointer head
    3. Operation-mode head
    4. Critic / value head

The action masks generated by environment.py are applied directly
to the policy logits before action sampling.

Expected observation
--------------------
obs["nodes_features"]:
    [B, N, 7]

obs["uav_state"]:
    [B, 3]

obs["ugv_state"]:
    [B, 2]

where:

    B = batch size
    N = number of nodes including the depot
"""

from __future__ import annotations

import math
from typing import Mapping

import torch
import torch.nn as nn
from torch import Tensor
from torch.distributions import Categorical

# ============================================================
# Constants
# ============================================================

NODE_FEATURE_DIM = 7
UAV_STATE_DIM = 3
UGV_STATE_DIM = 2

NUM_OPERATION_MODES = 2

# Maximum index supported by the scale embedding.
MAX_SCALE_INDEX = 199

# Mask value chosen instead of -inf / -1e9 because it is
# safe when using automatic mixed precision (float16).
MASKED_LOGIT_VALUE = -1.0e4


# ============================================================
# Transformer Policy
# ============================================================


class TransformerPolicy(nn.Module):
    """
    Transformer actor-critic policy for UAV-UGV routing.

    Parameters
    ----------
    in_nodes:
        Number of features for every task node.

        The current environment provides seven:

            x
            y
            visited
            relative_x_to_uav
            relative_y_to_uav
            relative_x_to_ugv
            relative_y_to_ugv

    embed_dim:
        Transformer embedding dimension.

    nhead:
        Number of attention heads.

    num_layers:
        Number of Transformer encoder layers.

    dropout:
        Dropout probability.

    max_scale_index:
        Maximum problem-size index represented by the scale embedding.
    """

    def __init__(
        self,
        in_nodes: int = NODE_FEATURE_DIM,
        embed_dim: int = 192,
        nhead: int = 6,
        num_layers: int = 3,
        dropout: float = 0.1,
        max_scale_index: int = MAX_SCALE_INDEX,
    ) -> None:
        super().__init__()

        if in_nodes <= 0:
            raise ValueError("in_nodes must be greater than 0.")

        if embed_dim <= 0:
            raise ValueError("embed_dim must be greater than 0.")

        if nhead <= 0:
            raise ValueError("nhead must be greater than 0.")

        if embed_dim % nhead != 0:
            raise ValueError("embed_dim must be divisible by nhead.")

        if num_layers <= 0:
            raise ValueError("num_layers must be greater than 0.")

        if not 0.0 <= dropout < 1.0:
            raise ValueError("dropout must be in [0, 1).")

        if max_scale_index < 1:
            raise ValueError("max_scale_index must be at least 1.")

        self.in_nodes = int(in_nodes)
        self.embed_dim = int(embed_dim)
        self.nhead = int(nhead)
        self.num_layers = int(num_layers)
        self.dropout = float(dropout)

        self.max_scale_index = int(max_scale_index)

        self.inv_sqrt_d = 1.0 / math.sqrt(self.embed_dim)

        # ====================================================
        # Node embedding
        # ====================================================

        self.node_embed = nn.Sequential(
            nn.Linear(
                self.in_nodes,
                self.embed_dim,
            ),
            nn.LayerNorm(self.embed_dim),
            nn.ReLU(),
            nn.Dropout(self.dropout),
        )

        # ====================================================
        # Transformer encoder
        # ====================================================

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=self.embed_dim,
            nhead=self.nhead,
            dim_feedforward=(self.embed_dim * 4),
            dropout=self.dropout,
            batch_first=True,
            activation="gelu",
            norm_first=True,
        )

        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=self.num_layers,
        )

        # ====================================================
        # UAV state embedding
        # ====================================================

        self.uav_embed = nn.Sequential(
            nn.Linear(
                UAV_STATE_DIM,
                self.embed_dim,
            ),
            nn.LayerNorm(self.embed_dim),
            nn.ReLU(),
        )

        # ====================================================
        # UGV state embedding
        # ====================================================

        self.ugv_embed = nn.Sequential(
            nn.Linear(
                UGV_STATE_DIM,
                self.embed_dim,
            ),
            nn.LayerNorm(self.embed_dim),
            nn.ReLU(),
        )

        # ====================================================
        # Problem-scale embedding
        # ====================================================

        self.scale_embed = nn.Embedding(
            self.max_scale_index + 1,
            self.embed_dim,
        )

        # ====================================================
        # Context fusion
        # ====================================================

        # Input consists of:
        #
        # graph embedding
        # + UAV embedding
        # + UGV embedding
        # + scale embedding
        #
        # therefore: embed_dim * 4.
        self.context_projection = nn.Sequential(
            nn.Linear(
                self.embed_dim * 4,
                self.embed_dim * 2,
            ),
            nn.LayerNorm(self.embed_dim * 2),
            nn.GELU(),
            nn.Dropout(self.dropout),
            nn.Linear(
                self.embed_dim * 2,
                self.embed_dim,
            ),
        )

        # ====================================================
        # Pointer-attention action heads
        # ====================================================

        # Query representing the desired UAV destination.
        self.uav_query = nn.Linear(
            self.embed_dim,
            self.embed_dim,
            bias=False,
        )

        # Query representing the desired UGV destination.
        self.ugv_query = nn.Linear(
            self.embed_dim,
            self.embed_dim,
            bias=False,
        )

        # Every encoded node receives a key representation.
        self.node_key = nn.Linear(
            self.embed_dim,
            self.embed_dim,
            bias=False,
        )

        # ====================================================
        # Operation-mode head
        # ====================================================

        self.mode_head = nn.Sequential(
            nn.Linear(
                self.embed_dim,
                self.embed_dim // 2,
            ),
            nn.ReLU(),
            nn.Dropout(self.dropout),
            nn.Linear(
                self.embed_dim // 2,
                NUM_OPERATION_MODES,
            ),
        )

        # ====================================================
        # Critic / value head
        # ====================================================

        self.critic = nn.Sequential(
            nn.Linear(
                self.embed_dim,
                self.embed_dim,
            ),
            nn.ReLU(),
            nn.Dropout(self.dropout),
            nn.Linear(
                self.embed_dim,
                self.embed_dim // 2,
            ),
            nn.ReLU(),
            nn.Linear(
                self.embed_dim // 2,
                1,
            ),
        )

    # ========================================================
    # Tensor-shape helpers
    # ========================================================

    @staticmethod
    def _ensure_batch_dim(
        tensor: Tensor,
        expected_single_dim: int,
    ) -> Tensor:
        """
        Add a batch dimension when a single observation is supplied.

        Example
        -------
        [N, 7] -> [1, N, 7]

        [3] -> [1, 3]
        """

        if tensor.dim() == expected_single_dim:
            return tensor.unsqueeze(0)

        return tensor

    @staticmethod
    def _ensure_mask_batch(
        mask: Tensor,
    ) -> Tensor:
        """
        Convert a single mask [N] into [1, N].
        """

        if mask.dim() == 1:
            return mask.unsqueeze(0)

        return mask

    # ========================================================
    # Encoding
    # ========================================================

    def _encode_batch(
        self,
        node_features: Tensor,
        uav_state: Tensor,
        ugv_state: Tensor,
        num_tasks: int | None = None,
    ) -> tuple[
        Tensor,
        Tensor,
        Tensor,
    ]:
        """
        Encode environment observations.

        Returns
        -------
        node_embeddings:
            [B, N, D]

        context:
            [B, D]

        node_keys:
            [B, N, D]
        """

        if node_features.dim() != 3:
            raise ValueError("node_features must have shape [B, N, F].")

        if node_features.size(-1) != self.in_nodes:
            raise ValueError(
                "Unexpected node feature dimension: "
                f"expected {self.in_nodes}, "
                f"got {node_features.size(-1)}."
            )

        batch_size = node_features.shape[0]

        # ----------------------------------------------------
        # Node encoding
        # ----------------------------------------------------

        node_embeddings = self.node_embed(node_features)

        node_embeddings = self.transformer(node_embeddings)

        # ----------------------------------------------------
        # Graph-level representation
        # ----------------------------------------------------

        graph_embedding = node_embeddings.mean(dim=1)

        # ----------------------------------------------------
        # Vehicle state representations
        # ----------------------------------------------------

        uav_context = self.uav_embed(uav_state)

        ugv_context = self.ugv_embed(ugv_state)

        # ----------------------------------------------------
        # Problem-scale representation
        # ----------------------------------------------------

        if num_tasks is None:

            # Number of nodes includes the depot,
            # while num_tasks normally excludes it.
            num_tasks = max(
                1,
                node_features.shape[1] - 1,
            )

        scale_index = min(
            max(
                int(num_tasks),
                0,
            ),
            self.max_scale_index,
        )

        scale_context = (
            self.scale_embed.weight[scale_index]
            .unsqueeze(0)
            .expand(
                batch_size,
                -1,
            )
        )

        # ----------------------------------------------------
        # Global context
        # ----------------------------------------------------

        combined_context = torch.cat(
            [
                graph_embedding,
                uav_context,
                ugv_context,
                scale_context,
            ],
            dim=-1,
        )

        context = self.context_projection(combined_context)

        # Keys are shared by UAV and UGV pointer heads.
        node_keys = self.node_key(node_embeddings)

        return (
            node_embeddings,
            context,
            node_keys,
        )

    # ========================================================
    # Logit computation
    # ========================================================

    def _compute_logits(
        self,
        context: Tensor,
        node_keys: Tensor,
    ) -> tuple[
        Tensor,
        Tensor,
        Tensor,
    ]:
        """
        Calculate UAV, UGV and mode logits.
        """

        # ----------------------------------------------------
        # UAV pointer
        # ----------------------------------------------------

        uav_query = self.uav_query(context).unsqueeze(1)

        # ----------------------------------------------------
        # UGV pointer
        # ----------------------------------------------------

        ugv_query = self.ugv_query(context).unsqueeze(1)

        node_keys_t = node_keys.transpose(
            1,
            2,
        )

        # Scaled dot-product pointer attention.
        uav_logits = (
            torch.bmm(
                uav_query,
                node_keys_t,
            ).squeeze(1)
            * self.inv_sqrt_d
        )

        ugv_logits = (
            torch.bmm(
                ugv_query,
                node_keys_t,
            ).squeeze(1)
            * self.inv_sqrt_d
        )

        # ----------------------------------------------------
        # Operating mode
        # ----------------------------------------------------

        mode_logits = self.mode_head(context)

        return (
            uav_logits,
            ugv_logits,
            mode_logits,
        )

    # ========================================================
    # Masking
    # ========================================================

    @staticmethod
    def _apply_mask(
        logits: Tensor,
        mask: Tensor,
    ) -> Tensor:
        """
        Apply a boolean action mask to logits.

        Invalid actions receive a very negative score.

        -1e4 is deliberately used instead of -inf because
        it behaves better with float16 automatic mixed precision.
        """

        mask = mask.to(
            dtype=torch.bool,
            device=logits.device,
        )

        return logits.masked_fill(
            ~mask,
            MASKED_LOGIT_VALUE,
        )

    # ========================================================
    # Single / normal forward
    # ========================================================

    def forward(
        self,
        obs: Mapping[str, Tensor],
        uav_mask: Tensor,
        ugv_mask: Tensor,
        mode_mask: Tensor,
        num_tasks: int | None = None,
    ) -> tuple[
        Categorical,
        Categorical,
        Categorical,
        Tensor,
    ]:
        """
        Forward pass used when selecting an action.

        Parameters
        ----------
        obs:
            Observation tensors.

        uav_mask:
            Valid UAV targets.

        ugv_mask:
            Valid UGV targets.

        mode_mask:
            Valid operating modes.

        num_tasks:
            Number of task nodes excluding the depot.

        Returns
        -------
        uav_distribution:
            Categorical distribution over UAV destinations.

        ugv_distribution:
            Categorical distribution over UGV destinations.

        mode_distribution:
            Categorical distribution over operation modes.

        values:
            Critic state value, shape [B, 1].
        """

        node_features = self._ensure_batch_dim(
            obs["nodes_features"],
            expected_single_dim=2,
        )

        uav_state = self._ensure_batch_dim(
            obs["uav_state"],
            expected_single_dim=1,
        )

        ugv_state = self._ensure_batch_dim(
            obs["ugv_state"],
            expected_single_dim=1,
        )

        uav_mask = self._ensure_mask_batch(uav_mask)

        ugv_mask = self._ensure_mask_batch(ugv_mask)

        mode_mask = self._ensure_mask_batch(mode_mask)

        _, context, node_keys = self._encode_batch(
            node_features=node_features,
            uav_state=uav_state,
            ugv_state=ugv_state,
            num_tasks=num_tasks,
        )

        (
            uav_logits,
            ugv_logits,
            mode_logits,
        ) = self._compute_logits(
            context=context,
            node_keys=node_keys,
        )

        uav_logits = self._apply_mask(
            uav_logits,
            uav_mask,
        )

        ugv_logits = self._apply_mask(
            ugv_logits,
            ugv_mask,
        )

        mode_logits = self._apply_mask(
            mode_logits,
            mode_mask,
        )

        values = self.critic(context)

        return (
            Categorical(logits=uav_logits),
            Categorical(logits=ugv_logits),
            Categorical(logits=mode_logits),
            values,
        )

    # ========================================================
    # Batched PPO / BC forward
    # ========================================================

    def batched_forward(
        self,
        observations: Mapping[str, Tensor],
        uav_masks: Tensor,
        ugv_masks: Tensor,
        mode_masks: Tensor,
        num_tasks: int | None = None,
    ) -> tuple[
        Tensor,
        Tensor,
        Tensor,
        Tensor,
    ]:
        """
        Batched forward pass used by PPO and Behavioral Cloning.

        Unlike ``forward()``, this method returns raw logits instead
        of Categorical distributions.

        Returns
        -------
        uav_logits:
            [B, N]

        ugv_logits:
            [B, N]

        mode_logits:
            [B, 2]

        values:
            [B]
        """

        node_features = observations["nodes_features"]

        uav_state = observations["uav_state"]

        ugv_state = observations["ugv_state"]

        _, context, node_keys = self._encode_batch(
            node_features=node_features,
            uav_state=uav_state,
            ugv_state=ugv_state,
            num_tasks=num_tasks,
        )

        (
            uav_logits,
            ugv_logits,
            mode_logits,
        ) = self._compute_logits(
            context=context,
            node_keys=node_keys,
        )

        uav_logits = self._apply_mask(
            uav_logits,
            uav_masks,
        )

        ugv_logits = self._apply_mask(
            ugv_logits,
            ugv_masks,
        )

        mode_logits = self._apply_mask(
            mode_logits,
            mode_masks,
        )

        values = self.critic(context).squeeze(-1)

        return (
            uav_logits,
            ugv_logits,
            mode_logits,
            values,
        )

    # ========================================================
    # Critic-only evaluation
    # ========================================================

    def value(
        self,
        obs: Mapping[str, Tensor],
        num_tasks: int | None = None,
    ) -> Tensor:
        """
        Estimate only the state value.

        Useful when an action distribution is not required.
        """

        node_features = self._ensure_batch_dim(
            obs["nodes_features"],
            expected_single_dim=2,
        )

        uav_state = self._ensure_batch_dim(
            obs["uav_state"],
            expected_single_dim=1,
        )

        ugv_state = self._ensure_batch_dim(
            obs["ugv_state"],
            expected_single_dim=1,
        )

        _, context, _ = self._encode_batch(
            node_features=node_features,
            uav_state=uav_state,
            ugv_state=ugv_state,
            num_tasks=num_tasks,
        )

        return self.critic(context)

    # ========================================================
    # Model information
    # ========================================================

    @property
    def num_parameters(self) -> int:
        """
        Number of trainable model parameters.
        """

        return sum(
            parameter.numel()
            for parameter in self.parameters()
            if parameter.requires_grad
        )


# ============================================================
# Scalable model
# ============================================================


class ScalableTransformerPolicy(TransformerPolicy):
    """
    Backward-compatible name used by the original training code.

    The architecture itself is identical to TransformerPolicy.
    Larger model capacity is selected through constructor arguments.

    Example
    -------
    Small / Medium:

        ScalableTransformerPolicy(
            embed_dim=192,
            nhead=6,
            num_layers=3,
        )

    Large:

        ScalableTransformerPolicy(
            embed_dim=256,
            nhead=8,
            num_layers=4,
        )
    """

    pass


# ============================================================
# Factory function
# ============================================================


def build_policy(
    *,
    is_large: bool = False,
    in_nodes: int = NODE_FEATURE_DIM,
    dropout: float = 0.1,
) -> TransformerPolicy:
    """
    Build a policy using the model sizes from the experiments.

    Small / Medium
    --------------
    embed_dim = 192
    nhead = 6
    num_layers = 3

    Large
    -----
    embed_dim = 256
    nhead = 8
    num_layers = 4
    """

    if is_large:

        return ScalableTransformerPolicy(
            in_nodes=in_nodes,
            embed_dim=256,
            nhead=8,
            num_layers=4,
            dropout=dropout,
        )

    return ScalableTransformerPolicy(
        in_nodes=in_nodes,
        embed_dim=192,
        nhead=6,
        num_layers=3,
        dropout=dropout,
    )


# ============================================================
# Public API
# ============================================================

__all__ = [
    "NODE_FEATURE_DIM",
    "UAV_STATE_DIM",
    "UGV_STATE_DIM",
    "NUM_OPERATION_MODES",
    "MASKED_LOGIT_VALUE",
    "TransformerPolicy",
    "ScalableTransformerPolicy",
    "build_policy",
]
