"""
Training pipeline for UAV-UGV cooperative routing.

The training process follows three stages:

    Phase 1: Behavioral Cloning (BC)
        Learn from expert trajectories generated by the
        heuristic / OR-Tools planner.

    Phase 2: PPO Fine-tuning
        Improve the policy through reinforcement learning.

    Phase 3: Self-Imitation Learning (SIL)
        Replay high-quality trajectories discovered by PPO.

Pipeline
--------

Heuristic / OR-Tools Expert
            |
            v
    Behavioral Cloning
            |
            v
      PPO Fine-tuning
            |
            v
   Best trajectory buffer
            |
            v
 Self-Imitation Learning
"""

from __future__ import annotations

import random
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Sequence

import numpy as np
import torch

from .agent import (
    SuperiorityAgent,
    Trajectory,
)
from .environment import UAVUGVEnv
from .heuristics import generate_expert_plan

# ============================================================
# Training configuration
# ============================================================


@dataclass
class TrainingConfig:
    """
    Configuration for the three-phase training pipeline.

    Default values are designed around the experiments from the
    original notebook.

    Parameters
    ----------
    bc_epochs:
        Number of Behavioral Cloning epochs.

    rl_episodes:
        Number of PPO fine-tuning episodes.

    sil_episodes:
        Number of Self-Imitation Learning episodes.

    learning_rate:
        Base learning rate used by the agent.

    bc_weight:
        Behavioral Cloning loss weight.

    sil_weight:
        Self-Imitation Learning weight.

    rl_temperature_start:
        Initial action-sampling temperature during PPO.

    rl_temperature_end:
        Final PPO action-sampling temperature.

    sil_temperature:
        Sampling temperature during SIL.

    max_steps_multiplier:
        Maximum environment steps are roughly:

            num_nodes * max_steps_multiplier

    expert_solver:
        Expert UAV route solver:

            "heuristic"
            "cpsat"

    cpsat_limit_s:
        Time limit for CP-SAT per UAV segment.

    save_best:
        Save the best valid policy checkpoint.

    checkpoint_path:
        Destination for the best checkpoint.

    seed:
        Random seed.
    """

    bc_epochs: int = 40
    rl_episodes: int = 160
    sil_episodes: int = 200

    learning_rate: float = 2e-4

    bc_weight: float = 1.0
    sil_weight: float = 0.5

    rl_temperature_start: float = 1.5
    rl_temperature_end: float = 0.7

    sil_temperature: float = 0.8

    max_steps_multiplier: int = 5

    expert_solver: str = "heuristic"
    cpsat_limit_s: float = 10.0

    save_best: bool = True
    checkpoint_path: str | None = None

    seed: int = 42

    def __post_init__(self) -> None:
        if self.bc_epochs < 0:
            raise ValueError("bc_epochs must be >= 0.")

        if self.rl_episodes < 0:
            raise ValueError("rl_episodes must be >= 0.")

        if self.sil_episodes < 0:
            raise ValueError("sil_episodes must be >= 0.")

        if self.learning_rate <= 0:
            raise ValueError("learning_rate must be > 0.")

        if self.rl_temperature_start <= 0:
            raise ValueError("rl_temperature_start must be > 0.")

        if self.rl_temperature_end <= 0:
            raise ValueError("rl_temperature_end must be > 0.")

        if self.sil_temperature <= 0:
            raise ValueError("sil_temperature must be > 0.")

        if self.max_steps_multiplier <= 0:
            raise ValueError("max_steps_multiplier must be > 0.")

        if self.expert_solver not in {
            "heuristic",
            "cpsat",
        }:
            raise ValueError(
                "expert_solver must be " "'heuristic' or 'cpsat'."
            )


# ============================================================
# Result container
# ============================================================


@dataclass
class TrainingResult:
    """
    Summary of one trained scenario.
    """

    num_tasks: int
    map_size: float

    baseline_makespan_s: float

    best_makespan_s: float | None
    best_energy_kj: float | None

    best_improvement_percent: float | None

    success: bool

    checkpoint_path: str | None

    history: list[dict[str, Any]]

    def to_dict(self) -> dict[str, Any]:
        """
        Convert result to dictionary.
        """

        return asdict(self)


# ============================================================
# Random seed
# ============================================================


def set_random_seed(
    seed: int,
) -> None:
    """
    Set random seeds for reproducible experiments.
    """

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


# ============================================================
# Observation helper
# ============================================================


def _copy_observation(
    observation: dict[str, np.ndarray],
) -> dict[str, np.ndarray]:
    """
    Deep-copy one environment observation.
    """

    return {key: value.copy() for key, value in observation.items()}


# ============================================================
# Empty trajectory
# ============================================================


def create_empty_trajectory() -> Trajectory:
    """
    Create an empty trajectory buffer compatible with agent.py.
    """

    return {
        "states": [],
        "actions": [],
        "logprobs": [],
        "rewards": [],
        "is_terminals": [],
        "uav_masks": [],
        "ugv_masks": [],
        "mode_masks": [],
    }


# ============================================================
# Expert trajectory collection
# ============================================================


def collect_expert_trajectory(
    env: UAVUGVEnv,
    expert_actions: Sequence[Sequence[int]],
    nodes: np.ndarray,
    map_size: float,
) -> Trajectory:
    """
    Replay an expert plan inside the environment.

    Expert mode disables the normal safety override because the
    expert planner already generated the demonstration.

    Permissive masks are stored during BC so that actions from the
    expert trajectory are not removed by the learned policy mask.

    Parameters
    ----------
    env:
        UAV-UGV environment.

    expert_actions:
        Actions produced by ``generate_expert_plan``.

    nodes:
        Fixed scenario coordinates.

    map_size:
        Scenario map size.

    Returns
    -------
    Trajectory
        Expert demonstration.
    """

    nodes = np.asarray(
        nodes,
        dtype=np.float32,
    )

    observation, _ = env.reset(
        options={
            "fixed_nodes": nodes,
            "map_size": map_size,
            "expert_mode": True,
        }
    )

    trajectory = create_empty_trajectory()

    env.set_expert_mode(True)

    total_reward = 0.0

    try:

        for action in expert_actions:

            if env.success:
                break

            expert_action = [
                int(action[0]),
                int(action[1]),
                int(action[2]),
            ]

            # --------------------------------------------
            # Defensive index clipping
            # --------------------------------------------

            expert_action[0] = min(
                max(
                    expert_action[0],
                    0,
                ),
                env.num_nodes - 1,
            )

            expert_action[1] = min(
                max(
                    expert_action[1],
                    0,
                ),
                env.num_nodes - 1,
            )

            expert_action[2] = min(
                max(
                    expert_action[2],
                    0,
                ),
                1,
            )

            # --------------------------------------------
            # Permissive BC masks
            # --------------------------------------------

            uav_mask = np.ones(
                env.num_nodes,
                dtype=bool,
            )

            ugv_mask = np.ones(
                env.num_nodes,
                dtype=bool,
            )

            mode_mask = np.ones(
                2,
                dtype=bool,
            )

            trajectory["states"].append(_copy_observation(observation))

            trajectory["actions"].append(expert_action.copy())

            trajectory["logprobs"].append(0.0)

            trajectory["uav_masks"].append(uav_mask)

            trajectory["ugv_masks"].append(ugv_mask)

            trajectory["mode_masks"].append(mode_mask)

            (
                next_observation,
                reward,
                terminated,
                truncated,
                _,
            ) = env.step(expert_action)

            done = terminated or truncated

            trajectory["rewards"].append(float(reward))

            trajectory["is_terminals"].append(done)

            total_reward += float(reward)

            observation = next_observation

            if done:
                break

    finally:

        env.set_expert_mode(False)

    trajectory["final_time"] = float(env.total_time_s)

    trajectory["total_energy_j"] = float(env.total_energy_J)

    trajectory["total_reward"] = float(total_reward)

    trajectory["success"] = bool(env.success)

    return trajectory


# ============================================================
# RL trajectory collection
# ============================================================


def collect_trajectory(
    env: UAVUGVEnv,
    agent: SuperiorityAgent,
    nodes: np.ndarray,
    map_size: float,
    *,
    temperature: float = 1.0,
    deterministic: bool = False,
    max_steps: int | None = None,
) -> Trajectory:
    """
    Run one episode and collect a PPO trajectory.

    Parameters
    ----------
    env:
        Environment.

    agent:
        RL agent.

    nodes:
        Fixed scenario nodes.

    map_size:
        Scenario map size.

    temperature:
        Action sampling temperature.

    deterministic:
        If True, choose argmax actions.

    max_steps:
        Optional local episode limit.

    Returns
    -------
    Trajectory
        Complete PPO-compatible trajectory.
    """

    nodes = np.asarray(
        nodes,
        dtype=np.float32,
    )

    observation, _ = env.reset(
        options={
            "fixed_nodes": nodes,
            "map_size": map_size,
            "expert_mode": False,
        }
    )

    env.set_expert_mode(False)

    trajectory = create_empty_trajectory()

    if max_steps is None:

        max_steps = env.num_nodes * env.max_steps_multiplier

    done = False

    step = 0
    total_reward = 0.0

    while not done and step < max_steps:

        (
            uav_mask,
            ugv_mask,
            mode_mask,
        ) = env.get_action_masks()

        (
            action,
            log_probability,
        ) = agent.select_action(
            observation,
            uav_mask,
            ugv_mask,
            mode_mask,
            temperature=temperature,
            deterministic=deterministic,
        )

        trajectory["states"].append(_copy_observation(observation))

        trajectory["actions"].append(action.copy())

        trajectory["logprobs"].append(float(log_probability))

        trajectory["uav_masks"].append(uav_mask.copy())

        trajectory["ugv_masks"].append(ugv_mask.copy())

        trajectory["mode_masks"].append(mode_mask.copy())

        (
            next_observation,
            reward,
            terminated,
            truncated,
            _,
        ) = env.step(action)

        done = terminated or truncated

        trajectory["rewards"].append(float(reward))

        trajectory["is_terminals"].append(done)

        total_reward += float(reward)

        observation = next_observation

        step += 1

    # Defensive terminal flag if a custom max_steps cut the
    # episode before the environment's own truncation.
    if (
        len(trajectory["is_terminals"]) > 0
        and step >= max_steps
        and not trajectory["is_terminals"][-1]
    ):
        trajectory["is_terminals"][-1] = True

    trajectory["final_time"] = float(env.total_time_s)

    trajectory["total_energy_j"] = float(env.total_energy_J)

    trajectory["total_reward"] = float(total_reward)

    trajectory["success"] = bool(env.success)

    trajectory["steps"] = int(step)

    trajectory["flying_steps"] = int(env.flying_steps)

    trajectory["riding_steps"] = int(env.riding_steps)

    return trajectory


# ============================================================
# Policy evaluation
# ============================================================


def evaluate_agent(
    env: UAVUGVEnv,
    agent: SuperiorityAgent,
    nodes: np.ndarray,
    map_size: float,
    *,
    deterministic: bool = True,
    temperature: float = 1.0,
) -> dict[str, Any]:
    """
    Evaluate the current policy without performing an update.
    """

    agent.eval()

    trajectory = collect_trajectory(
        env=env,
        agent=agent,
        nodes=nodes,
        map_size=map_size,
        temperature=temperature,
        deterministic=deterministic,
    )

    agent.train()

    flying_steps = int(trajectory["flying_steps"])

    riding_steps = int(trajectory["riding_steps"])

    total_motion_steps = flying_steps + riding_steps

    flying_ratio = flying_steps / max(
        1,
        total_motion_steps,
    )

    return {
        "success": bool(trajectory["success"]),
        "makespan_s": float(trajectory["final_time"]),
        "energy_kj": float(trajectory["total_energy_j"] / 1000.0),
        "total_reward": float(trajectory["total_reward"]),
        "steps": int(trajectory["steps"]),
        "flying_steps": (flying_steps),
        "riding_steps": (riding_steps),
        "flying_ratio": float(flying_ratio),
    }


# ============================================================
# Temperature schedule
# ============================================================


def linear_temperature_schedule(
    episode: int,
    total_episodes: int,
    start: float,
    end: float,
) -> float:
    """
    Linear temperature annealing.
    """

    if total_episodes <= 1:
        return float(end)

    progress = episode / (total_episodes - 1)

    progress = min(
        max(
            progress,
            0.0,
        ),
        1.0,
    )

    return float(start + (end - start) * progress)


# ============================================================
# Scale helper
# ============================================================


def infer_large_scale(
    num_tasks: int,
    map_size: float,
) -> bool:
    """
    Determine whether the large model configuration should be used.

    The project uses the large model for the 100-task / 40-km setup.
    """

    return bool(num_tasks >= 100 or map_size > 25.0)


# ============================================================
# History helper
# ============================================================


def _make_history_record(
    *,
    episode: int,
    phase: str,
    trajectory: Trajectory,
    baseline_makespan: float,
    actor_loss: float | None = None,
    critic_loss: float | None = None,
    entropy: float | None = None,
    bc_loss: float | None = None,
    sil_loss: float | None = None,
) -> dict[str, Any]:
    """
    Convert episode information into a serializable history record.
    """

    makespan = float(trajectory["final_time"])

    improvement = (
        (baseline_makespan - makespan) / baseline_makespan * 100.0
        if baseline_makespan > 0
        else 0.0
    )

    return {
        "episode": int(episode),
        "phase": phase,
        "success": bool(trajectory["success"]),
        "makespan_s": (makespan),
        "energy_kj": float(trajectory["total_energy_j"] / 1000.0),
        "reward": float(trajectory["total_reward"]),
        "vs_baseline_percent": float(improvement),
        "flying_steps": int(
            trajectory.get(
                "flying_steps",
                0,
            )
        ),
        "riding_steps": int(
            trajectory.get(
                "riding_steps",
                0,
            )
        ),
        "actor_loss": (actor_loss),
        "critic_loss": (critic_loss),
        "entropy": (entropy),
        "bc_loss": (bc_loss),
        "sil_loss": (sil_loss),
    }


# ============================================================
# Single-scenario training
# ============================================================


def train_scenario(
    nodes: np.ndarray,
    map_size: float,
    *,
    config: TrainingConfig | None = None,
    agent: SuperiorityAgent | None = None,
    env: UAVUGVEnv | None = None,
    is_large: bool | None = None,
    verbose: bool = True,
) -> tuple[
    SuperiorityAgent,
    TrainingResult,
]:
    """
    Train an agent on one fixed UAV-UGV scenario.

    Training phases
    ---------------
    1. Generate expert plan.
    2. Behavioral Cloning.
    3. PPO fine-tuning.
    4. Self-Imitation Learning.
    5. Return best model and statistics.

    Parameters
    ----------
    nodes:
        Node coordinates.

        nodes[0]:
            depot

        nodes[1:]:
            task nodes

    map_size:
        Map size in kilometres.

    config:
        Training configuration.

    agent:
        Optional pre-created agent.

    env:
        Optional pre-created environment.

    is_large:
        Override automatic model-size selection.

    verbose:
        Print progress.

    Returns
    -------
    agent
    result
    """

    if config is None:
        config = TrainingConfig()

    set_random_seed(config.seed)

    nodes = np.asarray(
        nodes,
        dtype=np.float32,
    )

    if nodes.ndim != 2 or nodes.shape[1] != 2:
        raise ValueError("nodes must have shape (num_nodes, 2).")

    if len(nodes) < 2:
        raise ValueError(
            "Scenario requires one depot " "and at least one task."
        )

    if map_size <= 0:
        raise ValueError("map_size must be > 0.")

    num_tasks = len(nodes) - 1

    if is_large is None:
        is_large = infer_large_scale(
            num_tasks,
            map_size,
        )

    # ========================================================
    # Environment
    # ========================================================

    if env is None:

        env = UAVUGVEnv(
            num_tasks=num_tasks,
            map_size=map_size,
            max_steps_multiplier=(config.max_steps_multiplier),
        )

    # ========================================================
    # Agent
    # ========================================================

    if agent is None:

        agent = SuperiorityAgent(
            num_tasks=num_tasks,
            is_large=is_large,
            lr=config.learning_rate,
            bc_weight=config.bc_weight,
            sil_weight=(
                0.6
                if (is_large and config.sil_weight == 0.5)
                else config.sil_weight
            ),
        )

    # ========================================================
    # Expert baseline
    # ========================================================

    if verbose:
        print("\n" + "=" * 72)
        print("Generating expert UAV-UGV plan...")

    (
        expert_plan,
        expert_actions,
    ) = generate_expert_plan(
        nodes_loc=nodes,
        map_size_km=map_size,
        uav_solver=(config.expert_solver),
        cpsat_limit_s=(config.cpsat_limit_s),
    )

    baseline_makespan = float(expert_plan.makespan_s)

    expert_trajectory = collect_expert_trajectory(
        env=env,
        expert_actions=expert_actions,
        nodes=nodes,
        map_size=map_size,
    )

    if verbose:
        print(f"Expert baseline: " f"{baseline_makespan:.2f} s")
        print(f"Expert actions: " f"{len(expert_actions)}")
        print("=" * 72)

    # ========================================================
    # Training state
    # ========================================================

    history: list[dict[str, Any]] = []

    best_makespan = float("inf")

    best_energy_kj: float | None = None

    best_success = False

    checkpoint_path: str | None = None

    global_episode = 0

    # ========================================================
    # Best-model helper
    # ========================================================

    def track_best(
        trajectory: Trajectory,
    ) -> bool:
        nonlocal best_makespan
        nonlocal best_energy_kj
        nonlocal best_success
        nonlocal checkpoint_path

        if not bool(trajectory["success"]):
            return False

        makespan = float(trajectory["final_time"])

        if makespan >= best_makespan:
            return False

        best_makespan = makespan

        best_energy_kj = float(trajectory["total_energy_j"] / 1000.0)

        best_success = True

        if config.save_best and config.checkpoint_path is not None:

            agent.save(config.checkpoint_path)

            checkpoint_path = str(config.checkpoint_path)

        return True

    # ========================================================
    # PHASE 1: Behavioral Cloning
    # ========================================================

    if config.bc_epochs > 0:

        if verbose:
            print("\n[Phase 1/3] " "Behavioral Cloning")

        for epoch in range(config.bc_epochs):

            global_episode += 1

            bc_loss = agent.behavioral_cloning_update([expert_trajectory])

            # Evaluate current BC policy.
            evaluation_trajectory = collect_trajectory(
                env=env,
                agent=agent,
                nodes=nodes,
                map_size=map_size,
                temperature=0.5,
                deterministic=False,
            )

            track_best(evaluation_trajectory)

            record = _make_history_record(
                episode=global_episode,
                phase="BC",
                trajectory=(evaluation_trajectory),
                baseline_makespan=(baseline_makespan),
                bc_loss=bc_loss,
            )

            history.append(record)

            if verbose and (
                epoch == 0
                or (epoch + 1) % 10 == 0
                or epoch == config.bc_epochs - 1
            ):

                status = "valid" if record["success"] else "invalid"

                print(
                    f"BC "
                    f"{epoch + 1:>4}/"
                    f"{config.bc_epochs} | "
                    f"loss="
                    f"{bc_loss:.4f} | "
                    f"time="
                    f"{record['makespan_s']:.2f}s | "
                    f"{status}"
                )

    # ========================================================
    # PHASE 2: PPO Fine-tuning
    # ========================================================

    if config.rl_episodes > 0:

        if verbose:
            print("\n[Phase 2/3] " "PPO Fine-tuning")

        for episode in range(config.rl_episodes):

            global_episode += 1

            temperature = linear_temperature_schedule(
                episode=episode,
                total_episodes=(config.rl_episodes),
                start=(config.rl_temperature_start),
                end=(config.rl_temperature_end),
            )

            trajectory = collect_trajectory(
                env=env,
                agent=agent,
                nodes=nodes,
                map_size=map_size,
                temperature=temperature,
            )

            # Large scenarios receive two PPO updates
            # per collected trajectory, matching the
            # original experimental training strategy.
            update_repeats = 2 if is_large else 1

            actor_loss = 0.0
            critic_loss = 0.0
            entropy = 0.0

            for _ in range(update_repeats):

                (
                    current_actor,
                    current_critic,
                    current_entropy,
                ) = agent.rl_update(trajectory)

                actor_loss += current_actor

                critic_loss += current_critic

                entropy += current_entropy

            actor_loss /= update_repeats

            critic_loss /= update_repeats

            entropy /= update_repeats

            # --------------------------------------------
            # Add superior trajectory to SIL buffer
            # --------------------------------------------

            if trajectory["success"]:

                agent.add_best_trajectory(
                    trajectory=trajectory,
                    makespan=float(trajectory["final_time"]),
                    baseline_makespan=(baseline_makespan),
                )

            new_best = track_best(trajectory)

            record = _make_history_record(
                episode=global_episode,
                phase="PPO",
                trajectory=trajectory,
                baseline_makespan=(baseline_makespan),
                actor_loss=(actor_loss),
                critic_loss=(critic_loss),
                entropy=(entropy),
            )

            history.append(record)

            log_interval = 25 if is_large else 20

            beat_baseline = (
                record["success"] and record["makespan_s"] < baseline_makespan
            )

            if verbose and (
                episode == 0
                or (episode + 1) % log_interval == 0
                or beat_baseline
                or new_best
            ):

                marker = ""

                if beat_baseline:
                    marker = " [BEAT BASELINE]"

                elif new_best:
                    marker = " [BEST]"

                print(
                    f"PPO "
                    f"{episode + 1:>4}/"
                    f"{config.rl_episodes} | "
                    f"T={temperature:.2f} | "
                    f"time="
                    f"{record['makespan_s']:.2f}s | "
                    f"energy="
                    f"{record['energy_kj']:.2f}kJ | "
                    f"vs expert="
                    f"{record['vs_baseline_percent']:+.2f}%"
                    f"{marker}"
                )

    # ========================================================
    # PHASE 3: Self-Imitation Learning
    # ========================================================

    if config.sil_episodes > 0:

        if verbose:
            print("\n[Phase 3/3] " "Self-Imitation Learning")

        for episode in range(config.sil_episodes):

            global_episode += 1

            trajectory = collect_trajectory(
                env=env,
                agent=agent,
                nodes=nodes,
                map_size=map_size,
                temperature=(config.sil_temperature),
            )

            # PPO update continues during the SIL stage.
            (
                actor_loss,
                critic_loss,
                entropy,
            ) = agent.rl_update(trajectory)

            # --------------------------------------------
            # Update superior trajectory buffer
            # --------------------------------------------

            if trajectory["success"]:

                agent.add_best_trajectory(
                    trajectory=trajectory,
                    makespan=float(trajectory["final_time"]),
                    baseline_makespan=(baseline_makespan),
                )

            # --------------------------------------------
            # Self-imitation update
            # --------------------------------------------

            sil_loss = 0.0

            if agent.sil_buffer_size > 0:

                sil_loss = agent.self_imitation_update()

            new_best = track_best(trajectory)

            record = _make_history_record(
                episode=global_episode,
                phase="SIL",
                trajectory=trajectory,
                baseline_makespan=(baseline_makespan),
                actor_loss=(actor_loss),
                critic_loss=(critic_loss),
                entropy=entropy,
                sil_loss=sil_loss,
            )

            history.append(record)

            log_interval = 25 if is_large else 20

            beat_baseline = (
                record["success"] and record["makespan_s"] < baseline_makespan
            )

            if verbose and (
                episode == 0
                or (episode + 1) % log_interval == 0
                or beat_baseline
                or new_best
            ):

                marker = ""

                if beat_baseline:
                    marker = " [BEAT BASELINE]"

                elif new_best:
                    marker = " [BEST]"

                print(
                    f"SIL "
                    f"{episode + 1:>4}/"
                    f"{config.sil_episodes} | "
                    f"time="
                    f"{record['makespan_s']:.2f}s | "
                    f"energy="
                    f"{record['energy_kj']:.2f}kJ | "
                    f"buffer="
                    f"{agent.sil_buffer_size} | "
                    f"vs expert="
                    f"{record['vs_baseline_percent']:+.2f}%"
                    f"{marker}"
                )

    # ========================================================
    # Final deterministic evaluation
    # ========================================================

    final_eval = evaluate_agent(
        env=env,
        agent=agent,
        nodes=nodes,
        map_size=map_size,
        deterministic=True,
    )

    final_trajectory: Trajectory = {
        "success": (final_eval["success"]),
        "final_time": (final_eval["makespan_s"]),
        "total_energy_j": (final_eval["energy_kj"] * 1000.0),
    }

    track_best(final_trajectory)

    # ========================================================
    # Result
    # ========================================================

    if best_success:

        best_improvement = (
            (baseline_makespan - best_makespan) / baseline_makespan * 100.0
            if baseline_makespan > 0
            else 0.0
        )

        result_best_makespan: float | None = float(best_makespan)

    else:

        best_improvement = None
        result_best_makespan = None

    result = TrainingResult(
        num_tasks=num_tasks,
        map_size=float(map_size),
        baseline_makespan_s=(baseline_makespan),
        best_makespan_s=(result_best_makespan),
        best_energy_kj=(best_energy_kj),
        best_improvement_percent=(best_improvement),
        success=(best_success),
        checkpoint_path=(checkpoint_path),
        history=history,
    )

    if verbose:

        print("\n" + "=" * 72)

        print("Training finished")

        print(f"Expert baseline : " f"{baseline_makespan:.2f} s")

        if best_success:

            print(f"Best RL time   : " f"{best_makespan:.2f} s")

            print(f"Best RL energy : " f"{best_energy_kj:.2f} kJ")

            print(f"Improvement    : " f"{best_improvement:+.2f}%")

        else:

            print("No valid RL solution found.")

        print("=" * 72)

    return (
        agent,
        result,
    )


# ============================================================
# Multiple-scenario training
# ============================================================


def train_scenarios(
    scenarios: Sequence[dict[str, Any]],
    *,
    config: TrainingConfig | None = None,
    checkpoint_dir: str | Path | None = None,
    verbose: bool = True,
) -> list[TrainingResult]:
    """
    Train one independent agent for every scenario.

    Expected scenario format
    ------------------------
    {
        "id": "small_01",
        "num_tasks": 30,
        "map_size": 16,
        "scale_name": "Small",
        "nodes_loc": [...]
    }

    ``nodes`` is also accepted instead of ``nodes_loc``.
    """

    if config is None:
        config = TrainingConfig()

    results: list[TrainingResult] = []

    for index, scenario in enumerate(scenarios):

        scenario_id = str(
            scenario.get(
                "id",
                f"scenario_{index + 1}",
            )
        )

        if "nodes_loc" in scenario:

            nodes = np.asarray(
                scenario["nodes_loc"],
                dtype=np.float32,
            )

        elif "nodes" in scenario:

            nodes = np.asarray(
                scenario["nodes"],
                dtype=np.float32,
            )

        else:

            raise KeyError(
                f"Scenario '{scenario_id}' "
                "does not contain "
                "'nodes_loc' or 'nodes'."
            )

        map_size = float(scenario["map_size"])

        scale_name = str(
            scenario.get(
                "scale_name",
                "",
            )
        ).lower()

        if scale_name:

            is_large = scale_name == "large"

        else:

            is_large = infer_large_scale(
                len(nodes) - 1,
                map_size,
            )

        # --------------------------------------------
        # Per-scenario config
        # --------------------------------------------

        scenario_config = TrainingConfig(**asdict(config))

        if checkpoint_dir is not None:

            checkpoint_directory = Path(checkpoint_dir)

            checkpoint_directory.mkdir(
                parents=True,
                exist_ok=True,
            )

            scenario_config.checkpoint_path = str(
                checkpoint_directory / (f"{scenario_id}.pth")
            )

        if verbose:

            print(
                f"\nScenario "
                f"{index + 1}/"
                f"{len(scenarios)}: "
                f"{scenario_id}"
            )

        _, result = train_scenario(
            nodes=nodes,
            map_size=map_size,
            config=scenario_config,
            is_large=is_large,
            verbose=verbose,
        )

        results.append(result)

    return results


# ============================================================
# Public API
# ============================================================

__all__ = [
    "TrainingConfig",
    "TrainingResult",
    "set_random_seed",
    "create_empty_trajectory",
    "collect_expert_trajectory",
    "collect_trajectory",
    "evaluate_agent",
    "linear_temperature_schedule",
    "infer_large_scale",
    "train_scenario",
    "train_scenarios",
]
